name: cached_network_image
description: Flutter library to load and cache network images
version: 0.2.0
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cached_network_image

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager:
    git:
      url: git://github.com/renefloor/flutter_cache_manager.git
      ref: develop

dev_dependencies:
  test: ^0.12.0