name: cached_network_image_platform_interface
description: Platform interface for CachedNetworkImage
version: 2.0.1
homepage: https://github.com/Baseflow/flutter_cached_network_image
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  file: '>=6.1.4 <8.0.0'
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
