name: cached_network_image
description: Flutter library to load and cache network images.
  Can also be used with placeholder and error widgets.
homepage: https://github.com/Baseflow/flutter_cached_network_image
version: 3.2.1

dependencies:
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  octo_image: ^1.0.0
  cached_network_image_platform_interface:
    git:
      url: https://github.com/Baseflow/flutter_cached_network_image.git
      ref: 97fbb84e4149e0fce8d8641c57d742531371407d
      path: cached_network_image_platform_interface
  cached_network_image_web:
    git:
      url: https://github.com/Baseflow/flutter_cached_network_image.git
      ref: 66e18eb5c9b89dd457a776e656bb6663cb9a784d
      path: cached_network_image_web


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
  flutter_lints: ^1.0.4
  file: ^6.1.0

environment:
  flutter: ">=3.3.0"
  sdk: ">=2.18.0 <3.0.0"
